# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Poll',
        ),
    ]
